posts_project/authentication/urls.py
from django.urls import path
from . import views

urlpatterns = [
    path('login', views.LoginView.as_view(), name='login'),
    path('logout', views.LogoutView.as_view()),
    path('registration', views.RegistrationView.as_view()),
    path('registration/successful', views.RegistrationSuccessfulView.as_view(), name="registration_successful"),
    path('profile/<int:pk>', views.UserProfileView.as_view(), name="user_profile"),
    path('password_reset/', views.PasswordResetView.as_view(), name='password_reset'),
    path('password_reset/done/', views.PasswordResetDoneView.as_view(), name='password_reset_done'),
    path('reset/<uidb64>/<token>/', views.PasswordResetConfirmView.as_view(), name='password_reset_confirm'),
    path('reset/done/', views.PasswordResetCompleteView.as_view(), name='password_reset_complete'),
]

posts_project/main/urls.py
from django.urls import path
from . import views

urlpatterns = [
    path('', views.index, name='index'),
]

posts_project/posts_project/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('account/', include('authentication.urls')),
    path('', include('main.urls')),
]

posts_project/authentication/models.py
from django.db import models
from django.contrib.auth.models import BaseUserManager, AbstractBaseUser, PermissionsMixin, Group


class CustomUserManager(BaseUserManager):
    def create_user(self, phone_number, email, password, is_superuser=False):
        """
        Creates and saves a User with the given email, date of
        birth and password.
        """
        if is_superuser:
            user = self.model(
                phone_number = phone_number,
            )
        else:
            if not email:
                raise ValueError('Пользователь должен иметь email-адрес')

            user = self.model(
                phone_number = phone_number,
                email=self.normalize_email(email),
            )

        user.set_password(password)
        user.save(using=self._db)

        return user

    def change_password(self, user_id, password):
        user = MyUser.objects.get(pk=user_id)
        user.set_password(password)
        user.save(using=self._db)

        return user

    def create_superuser(self, phone_number, password):
        user = self.create_user(
            phone_number,
            "",
            password,
            is_superuser=True,
        )

        user.is_admin = True
        user.save(using=self._db)

        return user


class CustomUser(AbstractBaseUser, PermissionsMixin):
    first_name = models.CharField("Имя", max_length=50)

    last_name = models.CharField("Фамилия", max_length=50)

    patronymic = models.CharField("Отчество", max_length=50, default="Не указано")

    email = models.EmailField(verbose_name="Email", max_length=255, unique=True, blank=True, null=True)

    phone_number = models.CharField("Номер телефона", max_length=255, unique=True, blank=False, null=False)

    avatar = models.ImageField("Изображение", upload_to='avatars', null=True, blank=True)

    is_superuser = models.BooleanField(default=False)
    is_active = models.BooleanField(default=True)
    is_admin = models.BooleanField(default=False)

    objects = CustomUserManager()

    created_at = models.DateTimeField("Дата создания", auto_now_add=True)

    updated_at = models.DateTimeField("Дата обновления", auto_now=True)

    USERNAME_FIELD = 'phone_number'
    REQUIRED_FIELDS = ['password']

    def __str__(self):
        return self.phone_number + " " + self.first_name

    def model_str(self):
        return self.phone_number

    def has_perm(self, perm, obj=None):
        "Does the user have a specific permission?"
        # Simplest possible answer: Yes, always
        return True

    def has_module_perms(self, app_label):
        "Does the user have permissions to view the app `app_label`?"
        # Simplest possible answer: Yes, always
        return True

    @property
    def is_staff(self):
        "Is the user a member of staff?"
        # Simplest possible answer: All admins are staff
        return self.is_admin

    class Meta:
        verbose_name = "Пользователь"
        verbose_name_plural = "Пользователи"

posts_project/authentication/forms.py
from django import forms
from django.contrib.auth.forms import UserCreationForm, PasswordChangeForm
from django.contrib.auth.models import Group
from authentication import models
from django.contrib.auth.password_validation import validate_password


"""USERS FORMS"""
class UserRegistrationForm(UserCreationForm):
    email = forms.EmailField()
    password1 = forms.CharField()
    password2 = forms.CharField()
    patronymic = forms.CharField(required=False)

    def clean_password2(self):
        password1 = self.cleaned_data.get("password1")
        password2 = self.cleaned_data.get("password2")
        if password1 and password2 and password1 != password2:
            raise forms.ValidationError(
                self.error_messages['password_mismatch'],
                code='password_mismatch',
            )
        return password2

    def save(self, commit=True):
        user = super(UserRegistrationForm, self).save(commit=False)
        user.set_password(self.cleaned_data["password1"])

        # Получение значения роли из формы
        role = 'Пользователь'

        if commit:
            user.save()

            # Получение или создание группы на основе выбранной роли
            user_group, created = Group.objects.get_or_create(name=role)
            # Добавление пользователя в группу
            user.groups.add(user_group)

        return user

    class Meta:
        model = models.CustomUser
        fields = (
            'phone_number', 
            'first_name', 
            'last_name', 
            'email', 
        )


class UserUpdateForm(forms.ModelForm):
    class Meta:
        model = models.CustomUser
        fields = (
            'phone_number',
            'first_name',
            'last_name',
            'patronymic',
            'email',
        )


class UserPasswordChangeForm(forms.ModelForm):
    id = forms.CharField(widget=forms.HiddenInput())
    password1 = forms.CharField(label="Пароль", widget=forms.PasswordInput())
    password2 = forms.CharField(label="Повторите пароль", widget=forms.PasswordInput())

    def clean(self):
        password1 = self.cleaned_data['password1']
        password2 = self.cleaned_data['password2']

        if password1 != password2:
            raise forms.ValidationError({"password1": "Пароли должны совпадать!"})

        return super().clean()

    def save(self, commit=False):
        id = self.cleaned_data['id']
        password1 = self.cleaned_data['password1']

        models.CustomUser.objects.change_password(id, password1)

        return super(UserPasswordChangeForm, self).save(commit=False)

    class Meta:
        model = models.CustomUser
        fields = ('id', 'password',)


class UserProfileForm(forms.ModelForm):
    class Meta:
        model = models.CustomUser
        fields = ['first_name', 'last_name', 'patronymic', 'email', 'phone_number', 'avatar',]

posts_project/authentication/views.py
from django.shortcuts import render
from django.http import HttpRequest, HttpResponse
from django.contrib.auth.mixins import LoginRequiredMixin, PermissionRequiredMixin
from django.contrib.auth.views import LoginView, LogoutView
from django.urls import reverse_lazy
from django.contrib import messages
from authentication import models, forms
from django.views.generic import CreateView, ListView, DetailView, UpdateView, DeleteView, TemplateView
from django.contrib.auth.views import PasswordResetView, PasswordResetConfirmView, PasswordResetDoneView, PasswordResetCompleteView, PasswordChangeView
from django.urls import reverse_lazy


class LoginView(LoginView):
    redirect_authenticated_user = True
    template_name='authentication/login.html'

    def get_success_url(self):
        return reverse_lazy('index')

    def form_invalid(self, form):
        messages.error(self.request,'Неправильный логин или пароль')
        return self.render_to_response(self.get_context_data(form=form))


class LogoutView(LogoutView):
    next_page = reverse_lazy('login')


class RegistrationView(CreateView):
    template_name = "authentication/registration.html"
    model = models.CustomUser
    form_class = forms.UserRegistrationForm
    success_url = reverse_lazy("registration_successful")

    def form_invalid(self, form):
        messages.error(self.request,'Неправильный логин или пароль')
        return self.render_to_response(self.get_context_data(form=form))


class RegistrationSuccessfulView(TemplateView):
    template_name = "authentication/registration_successful.html"


class PasswordResetView(PasswordResetView):
    template_name = 'authentication/password/password_reset_form.html'  # Кастомная страница ввода email
    email_template_name = 'authentication/password/password_reset_email.html'  # Кастомный шаблон email
    success_url = reverse_lazy('password_reset_done')

    # subject_template_name = 'auth/password/password_reset_email.txt'


class PasswordResetConfirmView(PasswordResetConfirmView):
    template_name = 'authentication/password/password_reset_confirm_form.html'  # Кастомная страница ввода нового пароля
    success_url = reverse_lazy('password_reset_complete')
    # reset_url_token = 'set-password'


class PasswordResetDoneView(PasswordResetDoneView):
    template_name = 'authentication/password/password_reset_done.html'  # Кастомная страница ввода нового пароля


class PasswordResetCompleteView(PasswordResetCompleteView):
    template_name = 'authentication/password/password_reset_complete.html'


class UserProfileView(UpdateView):
    model = models.CustomUser
    queryset = models.CustomUser.objects.all()
    form_class = forms.UserProfileForm
    template_name = 'authentication/profile.html'

    def get_success_url(self) -> str:
        success_url = '/account/profile/%s'%self.get_object().pk

        return success_url

posts_project/templates/authentication/login.html
{% extends "base.html" %}

{% block title %}Вход{% endblock %}
{% block content %}
    <div class="row">
        <div class="col-12 col-md-4 offset-md-4">
            <div class="card-new p-4">
                <h3 class="text-center mt-4">Вход в систему</h3>
                {% if form.non_field_errors %}
                    <div class="text-danger">
                        {% for error in form.non_field_errors %}
                            <p>{{ error }}</p>
                        {% endfor %}
                    </div>
                {% endif %}
                <form class="" method="post">
                    {% csrf_token %}
                    <div class="form-group">
                        <input type="text" id="" name="username" class="form-control" placeholder="Телефон">
                        {% if form.username.errors %}
                            <div class="text-danger">
                                {% for error in form.username.errors %}
                                    {{ error }}
                                {% endfor %}
                            </div>
                        {% endif %}
                    </div>
                    <div class="form-group">
                        <input type="password" id="" name="password" class="form-control" placeholder="Пароль">
                        {% if form.password.errors %}
                            <div class="text-danger">
                                {% for error in form.password.errors %}
                                    {{ error }}
                                {% endfor %}
                            </div>
                        {% endif %}
                    </div>
                    <div class="form-group">
                        <input type="submit" value="Войти" class="btn btn-outline-success btn-block">
                        <div class="d-flex justify-content-between">
                            <a href="/account/registration" class="pt-3">Регистрация</a>
                            <a href="/account/password_reset/" class="pt-3">Забыли пароль?</a>
                        </div>
                    </div>
                </form>
            </div>
        </div>
    </div>
{% endblock %}

posts_project/templates/authentication/profile.html
{% extends "base.html" %}
{% block content %}
    <form method="post" class="row" enctype="multipart/form-data">
        {% csrf_token %}
        <div class="col-12 col-sm-6 col-md-4 my-2">
            <div class="card-new p-4">
                <h3 class="text-center mt-4">Профиль пользователя</h3>
                <div class="form-group">
                    {% comment %} <label for="id_avatar">Изображение:</label> {% endcomment %}
                    <input type="file" id="id_avatar" name="avatar" class="form-control-file">
                    {% if request.user.avatar %}
                        <img id="avatar_preview" src="{{ request.user.avatar.url }}" class="img-fluid" alt="Avatar">
                    {% else %}
                        <img id="avatar_preview" src="/static/images/nophoto.jpg" class="img-fluid" alt="Avatar">
                    {% endif %}
                </div>
            </div>
        </div>
        <div class="col-12 col-sm-6 col-md-4 my-2">
            <div class="card-new p-4">
                <div class="form-group">
                    <label for="id_first_name">Имя:</label>
                    <input type="text" id="id_first_name" name="first_name" class="form-control" value="{{ request.user.first_name }}">
                </div>
                <div class="form-group">
                    <label for="id_last_name">Фамилия:</label>
                    <input type="text" id="id_last_name" name="last_name" class="form-control" value="{{ request.user.last_name }}">
                </div>
                <div class="form-group">
                    <label for="id_patronymic">Отчество:</label>
                    <input type="text" id="id_patronymic" name="patronymic" class="form-control" value="{{ request.user.patronymic }}">
                </div>
                <div class="form-group">
                    <label for="id_email">Email:</label>
                    <input type="email" id="id_email" name="email" class="form-control" value="{{ request.user.email }}">
                </div>
                <div class="form-group">
                    <label for="id_phone_number">Номер телефона:</label>
                    <input type="text" id="id_phone_number" name="phone_number" class="form-control" value="{{ request.user.phone_number }}">
                </div>
                <button type="submit" class="btn btn-primary">Сохранить изменения</button>
            </div>
        </div>
    </form>
{% endblock %}

posts_project/templates/authentication/registration.html
{% extends "base.html" %}

{% block title %}Регистрация{% endblock %}
{% block content %}
    <div class="row">
        <div class="col-12 col-md-4 offset-md-4 mt-4">
            <div class="card-new p-4">
                <h3 class="text-center mb-3">Регистрация</h3>
                <form class="" method="post">
                    {% csrf_token %}
                    <div class="form-group">
                        <input type="text" id="" name="phone_number" class="form-control" placeholder="Телефон">
                        {% if form.phone_number.errors %}
                            <div class="text-danger">
                                {% for error in form.phone_number.errors %}
                                    {{ error }}
                                {% endfor %}
                            </div>
                        {% endif %}
                    </div>
                    <div class="form-group">
                        <input type="email" id="" name="email" class="form-control" placeholder="Email">
                        {% if form.email.errors %}
                            <div class="text-danger">
                                {% for error in form.email.errors %}
                                    {{ error }}
                                {% endfor %}
                            </div>
                        {% endif %}
                    </div>
                    <div class="form-group">
                        <input type="text" id="" name="first_name" class="form-control" placeholder="Имя">
                        {% if form.first_name.errors %}
                            <div class="text-danger">
                                {% for error in form.first_name.errors %}
                                    {{ error }}
                                {% endfor %}
                            </div>
                        {% endif %}
                    </div>
                    <div class="form-group">
                        <input type="text" id="" name="last_name" class="form-control" placeholder="Фамилия">
                        {% if form.last_name.errors %}
                            <div class="text-danger">
                                {% for error in form.last_name.errors %}
                                    {{ error }}
                                {% endfor %}
                            </div>
                        {% endif %}
                    </div>
                    <div class="form-group">
                        <input type="text" id="" name="patronymic" class="form-control" placeholder="Отчество">
                        {% if form.patronymic.errors %}
                            <div class="text-danger">
                                {% for error in form.patronymic.errors %}
                                    {{ error }}
                                {% endfor %}
                            </div>
                        {% endif %}
                    </div>
                    <div class="form-group">
                        <input type="password" id="" name="password1" class="form-control" placeholder="Пароль">
                        {% if form.password1.errors %}
                            <div class="text-danger">
                                {% for error in form.password1.errors %}
                                    {{ error }}
                                {% endfor %}
                            </div>
                        {% endif %}
                    </div>
                    <div class="form-group">
                        <input type="password" id="" name="password2" class="form-control" placeholder="Повторите пароль">
                        {% if form.password2.errors %}
                            <div class="text-danger">
                                {% for error in form.password2.errors %}
                                    {{ error }}
                                {% endfor %}
                            </div>
                        {% endif %}
                    </div>
                    <div class="form-group">
                        <input type="submit" value="Зарегистрироваться" class="btn btn-outline-success btn-block">
                    </div>
                </form>
            </div>
        </div>
    </div>
{% endblock %}

posts_project/templates/authentication/registration_successful.html
{% extends "base.html" %}

{% block title %}Регистрация{% endblock %}
{% block content %}
    <div class="container">
        <div class="row">
            <div class="col-12" style="margin-top: 200px;">
                <h3 class="text-center mb-3">Вы успешно зарегистрированы!</h3>
            </div>
        </div>
    </div>
{% endblock %}